version: '3'
services: 
  docsify:
    image: littlstar/docker-docsify
    volumes:
      - ./docs:/usr/local/docsify
    ports:
      - 3199:3000
    network_mode: bridge
    labels:
    - traefik.backend=docs
    - traefik.frontend.rule=Host:docs.bieccamvd.com
    - traefik.docker.network=bridge
    - traefik.port=3199